package com.ljw.ssm.mapper;

import com.ljw.ssm.entity.Product;
import com.ljw.ssm.entity.ProductExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    // 查询某个分类下的所有分类并分页
	List<Product> productAllPageGet(@Param("id")Integer id,@Param("keyword") String keyword);

	// 保存产品
	void saveProduct(@Param("name")String name, @Param("subTitle")String subTitle, @Param("originalPrice")Float originalPrice, 
			@Param("promotePrice")Float promotePrice, @Param("stock")Integer stock, @Param("cid")Integer cid,
			@Param("pictname")String pictname, @Param("date")Date date);

	// 更新
	void updateProduct(@Param("name")String name, @Param("subTitle")String subTitle, @Param("originalPrice")Float originalPrice, 
			@Param("promotePrice")Float promotePrice, @Param("stock")Integer stock, @Param("cid")Integer cid,
			@Param("pictname")String pictname,@Param("id")Integer id);
}