package com.ljw.ssm.mapper;

import com.ljw.ssm.entity.ProductImages;
import com.ljw.ssm.entity.ProductImagesExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ProductImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimages
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimages
     *
     * @mbggenerated
     */
    int insert(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimages
     *
     * @mbggenerated
     */
    int insertSelective(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimages
     *
     * @mbggenerated
     */
    List<ProductImages> selectByExample(ProductImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimages
     *
     * @mbggenerated
     */
    ProductImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimages
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimages
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductImages record);

    // ±£¥ÊœÍ«ÈÕº∆¨
	void saveImages(@Param("pid")Integer pid, @Param("type")String type);

	// ≤È’“œÍ«ÈÕº∆¨
	List<ProductImages> selectAllImages(@Param("pid")Integer pid);
}