package com.ljw.ssm.mapper;

import com.ljw.ssm.entity.Property;
import com.ljw.ssm.entity.PropertyValue;
import com.ljw.ssm.entity.PropertyValueExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int insert(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int insertSelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    List<PropertyValue> selectByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    PropertyValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PropertyValue record);

    // 根据产品id查询属性值
	List<PropertyValue> getPid(@Param("pid")Integer pid);

	
	// 查找属性名
	List<Property> selectByPropertyName(@Param("pid")Integer pid);

	// 修改或者添加属性值
	void AddAndEdit(@Param("pid")Integer pid, @Param("ptid")Integer ptid, @Param("value")String value);
}