package com.ljw.ssm.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ljw.ssm.entity.Role;
import com.ljw.ssm.entity.RoleExample;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Fri Jul 03 13:33:32 CST 2020
     */
    int updateByPrimaryKey(Role record);
    
    // 查询、关键字查询(角色分页)
    List<Role> selectRoleByKeyword(String keyword);
    /**
     * 查询已分配
     * @param adminId
     * @return
     */
	List<Role> selectAssignedRole(Integer adminId);
	/**
	 * 查询未分配
	 */
	List<Role> selectUnAssignedRole(Integer adminId);

	/**
	 *  查找跟这个adminId关联的角色
	 */
	List<Role> getAllocated(Integer adminId);

	/**
	 *  查找跟这个adminId没有关联的角色
	 */
	List<Role> getUndestrbuted(Integer adminId);
}