package com.ljw.ssm.entity;

import java.io.Serializable;

public class Auth implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.id
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.name
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.title
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.category_id
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    private Integer categoryId;
    
    
    
    

    public Auth() {
		super();
		// TODO Auto-generated constructor stub
	}

    
	public Auth(Integer id, String name, String title, Integer categoryId) {
		super();
		this.id = id;
		this.name = name;
		this.title = title;
		this.categoryId = categoryId;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.id
     *
     * @return the value of t_auth.id
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.id
     *
     * @param id the value for t_auth.id
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.name
     *
     * @return the value of t_auth.name
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.name
     *
     * @param name the value for t_auth.name
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.title
     *
     * @return the value of t_auth.title
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.title
     *
     * @param title the value for t_auth.title
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.category_id
     *
     * @return the value of t_auth.category_id
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.category_id
     *
     * @param categoryId the value for t_auth.category_id
     *
     * @mbggenerated Tue Jul 07 11:19:21 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }


	@Override
	public String toString() {
		return "Auth [id=" + id + ", name=" + name + ", title=" + title + ", categoryId=" + categoryId + "]";
	}
    
}